version: '3'

services:
  app:
    container_name: fc2-node-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/home/node/app'
    image: typevitor/nodeapp
    depends_on:
      db:
        condition: service_healthy    
    networks:
      - node-net
      - node-back

  web:
    container_name: fc2-nginx
    ports:
    - "8080:80"
    image: nginx:alpine3.20-slim
    volumes:
      - '.docker/nginx:/etc/nginx/conf.d/'
    depends_on:
      - app
    networks:
      - node-net

  db:
    container_name: fc2-db
    image: mysql:8.0.39
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fc2-db
      MYSQL_USER: fc2-user
      MYSQL_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-ppass"]
      interval: 5s
      timeout: 10s
      retries: 10
    volumes:
      - "./.docker/mysql/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - app-db:/var/lib/mysql
    networks:
      - node-back

volumes:
  app-db:

networks:
  node-net: 
    driver: bridge
  node-back: 
    driver: bridge